name: kaobei
description: "使用flutter编写的三方拷贝漫画"
version: 1.2.2+8

environment:
  sdk: ^3.7.0-323.0.dev

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # ================== 核心框架 ==================
  bloc: ^9.0.0                  # BLoC 核心库（状态管理）
  flutter_bloc: ^9.0.0          # BLoC 的 Flutter 集成
  bloc_concurrency: ^0.3.0      # BLoC 事件并发控制
  mobx: ^2.5.0                  # 响应式状态管理方案
  flutter_mobx: ^2.3.0          # MobX 的 Flutter 绑定

  # ================== UI 组件与交互 ==================
  cupertino_icons: ^1.0.8             # iOS 风格图标库
  dynamic_color: ^1.7.0               # Material You 动态主题支持
  loading_animation_widget: ^1.2.1    # 60+ 精美加载动画集合
  toastification: ^3.0.1              # 现代化通知提示系统
  animated_search_bar: ^2.7.2         # 带动画效果的搜索栏组件
  photo_view: ^0.15.0                 # 支持缩放/平移的图片查看器
  scrollable_positioned_list: ^0.3.8  # 可精确定位的滚动列表
  persistent_bottom_nav_bar: ^6.2.1   # 持久化底部导航栏解决方案
  flutter_markdown: ^0.7.6+2          # Markdown 内容渲染组件
  flutter_colorpicker: ^1.1.0         # 颜色选择器组件
  flutter_sticky_header: ^0.7.0       # 粘性头部组件

  # ================== 数据持久化 ==================
  hive_ce: ^2.10.1                # 轻量级键值对数据库
  hive_ce_flutter: ^2.2.0        # hive_ce 的 Flutter 适配层
  objectbox: ^4.0.3              # 高性能对象数据库
  objectbox_flutter_libs: ^4.0.3 # ObjectBox 的 Flutter 支持

  # ================== 网络与通信 ==================
  dio: ^5.6.0                    # 强大的 HTTP 客户端库
  webview_flutter: ^4.10.0       # 原生 WebView 组件
  url_launcher: ^6.3.1           # URL 启动器（打开外部链接）
  connectivity_plus: ^6.1.3      # 网络连接状态监听

  # ================== 数据处理与序列化 ==================
  json_annotation: ^4.9.0        # JSON 序列化注解
  json_serializable: ^6.8.0      # JSON 序列化代码生成
  freezed: ^2.5.7                # 不可变数据类生成（类似 Kotlin data class）
  freezed_annotation: ^2.4.4     # Freezed 注解支持
  crypto: ^3.0.6                 # 常用加密算法集合（MD5/SHA等）
  encrypt: ^5.0.3                # 加密/解密工具包（AES/RSA等）
  archive: ^4.0.2                # 压缩/解压缩工具（ZIP/TAR等）

  # ================== 系统交互与设备功能 ==================
  path_provider: ^2.1.5          # 获取系统路径（文档/临时目录等）
  open_file: ^3.5.10             # 跨平台文件打开功能
  image_picker: ^1.1.2           # 图片选择器（相册/相机）
  image_cropper: ^9.0.0          # 图片裁剪组件
  package_info_plus: ^8.2.1      # 获取应用包信息（版本号等）
  permission_guard: ^2.0.1       # 权限申请与管理工具
  wakelock_plus: ^1.2.10         # 屏幕常亮组件

  # ================== 工具与工具类 ==================
  event_bus: ^2.0.1              # 事件总线（发布-订阅模式）
  uuid: ^4.4.2                   # UUID 生成器
  equatable: ^2.0.3              # 简化对象相等性比较
  collection: ^1.18.0            # Dart 集合扩展工具
  stream_transform: ^2.1.1       # 流数据处理工具包
  path: ^1.9.0                   # 跨平台路径处理库
  flutter_svg: ^2.0.17           # SVG 图形渲染库
  flutter_svg_provider: ^1.0.7   # SVG 资源加载器

  # ================== 路由与导航 ==================
  auto_route: ^9.2.2             # 类型安全的路由管理方案

  # ================== 图像处理 ==================
  image: ^4.5.2                  # 图像编解码与处理库

  # ================== 错误监控 ==================
  stack_trace: ^1.12.0          # 异常堆栈解析
  logger: ^2.5.0                # 日志打印

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0           # 代码规范检查工具

  # ================== 代码生成工具 ==================
  build_runner: ^2.4.14           # 代码生成器运行核心
  mobx_codegen: ^2.7.0            # MobX 代码生成器
  auto_route_generator: ^9.0.0    # 路由代码生成器
  hive_ce_generator: ^1.8.1       # hive_ce 模型生成器
  objectbox_generator: ^4.0.3     # ObjectBox 模型生成器

flutter:
  uses-material-design: true

  # 资源文件配置
#  assets:

objectbox:
  # Writes objectbox-model.json and objectbox.g.dart to lib/custom (and test/custom).
  output_dir:
    lib: object_box
    test: object_box